import { NextResponse } from "next/server";
import { requirePermission, AuthError } from "@/lib/auth/permissions";
import nodemailer from "nodemailer";
import { EMAIL_CONFIG } from "@/lib/emailConfig";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await requirePermission("investigation:read");
    const { id } = await params;
    const body = await req.json();

    const recipient = body.recipient || EMAIL_CONFIG.DEFAULT_RECIPIENT;
    const subject = body.subject || `ARGUS Investigation Brief — ${body.investigationTitle || "Question Mark"}`;
    const pdfBase64 = body.pdfBase64;
    const filename = body.filename || `ARGUS_Investigation_Brief_${(body.investigationTitle || "Investigation").replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

    if (!pdfBase64) {
      return NextResponse.json({ error: "PDF content is missing" }, { status: 400 });
    }

    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;

    if (!emailUser || !emailPass) {
      return NextResponse.json(
        { error: "SMTP credentials (EMAIL_USER / EMAIL_PASS) are not configured on the server." },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: emailUser,
        pass: emailPass,
      },
    });

    const htmlBody = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: 'Times New Roman', serif; background-color: #fcfbf9; color: #1a1a1a; margin: 0; padding: 24px; }
            .card { max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #e5e5e0; padding: 32px; border-radius: 6px; }
            .header { border-b: 2px solid #d97706; padding-bottom: 12px; margin-bottom: 20px; }
            .tag { font-family: monospace; font-size: 10px; color: #d97706; text-transform: uppercase; letter-spacing: 1.5px; }
            .title { font-size: 20px; font-weight: bold; margin: 4px 0 0 0; }
            .meta { font-family: monospace; font-size: 11px; color: #666666; margin-top: 16px; padding: 12px; background: #f9f8f6; border-radius: 4px; }
            .content { font-size: 13px; line-height: 1.6; color: #333333; margin-top: 20px; }
            .footer { margin-top: 32px; border-top: 1px solid #e5e5e0; pt: 16px; font-family: monospace; font-size: 10px; color: #888888; text-align: center; }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="header">
              <div class="tag">ARGUS OMNISCIENT EVIDENCE INTELLIGENCE PLATFORM</div>
              <div class="title">OFFICIAL INVESTIGATION BRIEF</div>
            </div>

            <p class="content">
              Hello,<br/><br/>
              An official Investigation Brief has been compiled and generated for:
            </p>

            <div class="meta">
              <strong>INVESTIGATION:</strong> ${body.investigationTitle || "Question Mark"}<br/>
              <strong>CASE NUMBER:</strong> ${body.caseNumber || "QM-2026-01"}<br/>
              <strong>STATUS:</strong> ACTIVE / GROUNDED EVIDENCE<br/>
              <strong>ATTACHMENT:</strong> ${filename}
            </div>

            <p class="content">
              The complete intelligence report is attached as a PDF document. It contains structured key findings, bridge analysis, financial trail metrics, temporal reconstruction, evidence provenance, and investigator conclusions.
            </p>

            <div class="footer">
              CONFIDENTIAL INVESTIGATION MATERIAL · GENERATED BY ARGUS<br/>
              © 2026 ARGUS Evidence Intelligence System
            </div>
          </div>
        </body>
      </html>
    `;

    const pdfBuffer = Buffer.from(pdfBase64.replace(/^data:application\/pdf;base64,/, ""), "base64");

    await transporter.sendMail({
      from: `"ARGUS System" <${emailUser}>`,
      to: recipient,
      subject: subject,
      html: htmlBody,
      attachments: [
        {
          filename: filename,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    return NextResponse.json({ success: true, message: "Email sent successfully", recipient, timestamp: new Date().toISOString() });
  } catch (err: any) {
    if (err instanceof AuthError) {
      return NextResponse.json({ error: err.message }, { status: 403 });
    }
    return NextResponse.json(
      { error: err?.message || "Failed to send email" },
      { status: 500 }
    );
  }
}
